### ISSUE TITLE
Integers should be formatted as strings in responses

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#106]
Integers should be formatted as strings in responses

**Comment by DmitryBespalov** [comment]
In responses of the following endpoints:

POST /v2/safes/ 
- payment
- gasEstimated
- gasPriceEstimated

POST /v2/safes/estimates/
- gas
- gasPrice
- payment

POST /v1/safes/{address}/transactions/estimates/
- safeTxGas
- operationalGas
- estimations.baseGas
- estimations.gasPrice

GET /v2/safes/{address}/funded/
- blockNumber

**Comment by Uxio0** [comment]
@rmeissner As some endpoints are already being used by Android, do you agree with these changes?

**Comment by DmitryBespalov** [comment]
Also we need a new version of  /api/v1/safes/\(safe)/transactions/estimate/ - v2
- safeTxGas
- baseGas
- dataGas
- gasPrice
- operationalGas
