### ISSUE TITLE
POST /v2/auth returned a different owner address than it was signed with.

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-relay-service#111]
As reported by iOS logging feature, on May 31st, there was 1 auth request that was registering wrong owner. 

Please check the signature recovery.

Expected response

```
"(extension in MultisigWalletImplementations):MultisigWalletDomainModel.AuthRequest.AuthResponseItem(owner: "0x55b22Fe5CdBaD9da61a46792cb8F8B68710f719A", pushToken: "e2BXHhyMb2o:APA91bFRH-NJUNLGHL6Vm29FoZ_EDpgZu0bdHrmJMFFjEqMsdyN3dy02GeFiENghXtVh4H5wSg7YU5jFIe11_TXYJUY6shZ7Z-W7B6NXIcS2quuCVSG_tLTljFBVfdRQoaYheZshpHQ0", client: "ios", buildNumber: 2, versionName: "1.2.0", bundle: "io.gnosis.safe")"
```

Actual response

```
"(extension in MultisigWalletImplementations):MultisigWalletDomainModel.AuthRequest.AuthResponseItem(owner: "0xbA37cB8ddf1FeAaf0859687A3671d5500B7cA74F", pushToken: "e2BXHhyMb2o:APA91bFRH-NJUNLGHL6Vm29FoZ_EDpgZu0bdHrmJMFFjEqMsdyN3dy02GeFiENghXtVh4H5wSg7YU5jFIe11_TXYJUY6shZ7Z-W7B6NXIcS2quuCVSG_tLTljFBVfdRQoaYheZshpHQ0", client: "ios", buildNumber: 2, versionName: "1.2.0", bundle: "io.gnosis.safe")"
```

Basically, the device owner address is 0x55b22Fe5CdBaD9da61a46792cb8F8B68710f719A, but it was registered on the backend with 0xbA37cB8ddf1FeAaf0859687A3671d5500B7cA74F. The consequence is that device won't get notifications if the registered address is not the owner of the safe.

Reference:
https://fabric.io/gnosis/ios/apps/io.gnosis.safe/issues/5cef3621f8b88c296343f6cd?utm_medium=service_hooks-github&utm_source=issue_impact

**Comment by Uxio0** [comment]
This is related with the notification service, but talking to Dima it seems it might be a bug in the app. If it happens again we will reopen the issue.
