### ISSUE TITLE
GET ​/v1​/private​/safes​/ returns negative balance for some safes

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#112]
Examples can be found in https://docs.google.com/spreadsheets/d/1pmKwYDB29SVjP1dggA5zZEq40HoHfisTSLM13THWEm0/edit#gid=0

**Comment by Uxio0** [comment]
@tschubotz It seems that some Safes where funded even months ago from their deployment. Internal tx task gets the safe deployment block and scans a few days before, but not so much. As the funding tx is missing, balance is miscalculated.

I will push a hotfix for that

**Comment by Uxio0** [comment]
I found another bug, errored txs were processed as if the tx were effective
