### ISSUE TITLE
Add DESH token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#114]
Please add the DESH token
- https://etherscan.io/token/0x28F2c01a3D86eE4faf037147f0aEb49C2Eab47ce
- Logo: https://drive.google.com/open?id=1rEWRZfSI1F8C7pqB5y_HXYJswNYT1oni

**Comment by Uxio0** [comment]
@tschubotz https://safe-relay.gnosis.pm/api/v1/tokens/?search=DESH
