### ISSUE TITLE
Add PITCH token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#115]
Please add the PITCH token to our token list.
- https://etherscan.io/token/0x87f56ee356b434187105b40f96b230f5283c0ab4
- Logo as SVG: https://drive.google.com/open?id=1XAz-aIex3lCxb-x3n7TERcx4qDX8Zf20

**Comment by shinsyotta** [comment]
Vector logo:
https://mega.nz/#!0SxAgaSY!_0N1SBXHEVWp05DBapOFqEje1jNh2wbUzkdYfklTgiY

**Comment by Uxio0** [comment]
@tschubotz https://safe-relay.gnosis.pm/api/v1/tokens/?search=PITCH
