### ISSUE TITLE
Add endpoint that returns tokens for a Safe

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-relay-service#116]
See epic for details

* should display Ether balance and balances of all ERC20 tokens with balance > 0

**Edit by Uxío:**
New endpoint is `GET /api/v1/safes/<str:address>/balances/`. It will return the following for tokens with `value > 0`:

`[{"tokenAddress": "<address>", "balance": "<int">}...]`

Ether balance is returned also with `tokenAddress=null`, even if `balance==0`

**Comment by Uxio0** [comment]
@tschubotz @rmeissner I think it would be useful to also show tokens the user has operated with but now have zero balance, what do you think?

**Comment by tschubotz** [comment]
Hm, I think that's unnecessary to be honest. It would add some not needed complexity I think.
