### ISSUE TITLE
Use better DAI token image

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#117]
We currently have a DAI image with a weird background: https://gnosis-safe-token-logos.s3.amazonaws.com/0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359.png

Especially on Android this looks a bit ugly.

We are promoting DAI as token payment options, hence I think we should get this logo straight.

Better version: https://github.com/gnosis/dx-react/blob/master/src/assets/tokens/DAI.svg

Could you please update it when you get a chance? :)

**Comment by Uxio0** [comment]
@tschubotz Updated https://gnosis-safe-token-logos.s3.amazonaws.com/0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359.png :)
