### ISSUE TITLE
Estimating transactions for all possible tokens takes too long on Rinkeby

### ISSUE THREAD

**Issue by sche** [gnosis/safe-relay-service#119]
It takes more than 10 sec on Rinkeby now.

**Comment by Uxio0** [comment]
Hi @sche, are you using rinkeby staging or production?

**Comment by sche** [comment]
I use staging

**Comment by Uxio0** [comment]
Hi @sche, I have updated the oracles to use the same as in production mainnet (even though prices are not the same) and removed some centralized oracles. It should go faster now.

Can you confirm that?

**Comment by sche** [comment]
I will check that.
I am testing the production now, and for Safe creating estimations it took me ~6 sec.

**Comment by Uxio0** [comment]
@sche I'm checking, for me is about 3 seconds. Ethereum node must be called for every estimation (as it could be different depending on the token and the storage status), so it seems alright. I could do it in parallel but I don't want to stress the node. Prices are cached so they shouldn't be a problem.

@rmeissner @sche Do you think this response time is ok or should I try to improve it?

**Comment by rmeissner** [comment]
hmm 6 sec would be kind of the limit (the android client has a timeout of 10 sec) ... it is an estimate I think for that endpoint it might even be fine if it is not 100% accurate (so only get the required gas once from the node) ... but if we do that we should document this

**Comment by Uxio0** [comment]
@DmitryBespalov @sche @rmeissner I will fix this issue doing an "estimation of the estimation" (I will use eth estimation and add some fixed gas for token payments), so for sending txs you should always call the individual estimation after the token/eth is selected.

**Comment by sche** [comment]
@Uxio0 your proposal is relevant to this product ticket https://github.com/gnosis/safe/issues/184
Is it possible to avoid re-estimating in general? @rmeissner @tschubotz

**Comment by Uxio0** [comment]
@sche No, it doesn't affect that ticket. It's just that you need to confirm the costs using the regular `/estimate/` endpoint after making a choice from the `/estimates/` endpoint.

We cannot have everything, short times for estimating multiple tokens and avoid re-estimating after that :(

**Comment by Uxio0** [comment]
@sche @rmeissner @DmitryBespalov I have just deployed it in Staging and Rinkeby prod

**Comment by Uxio0** [comment]
@rmeissner Suggested testing with batch requests to the node to speed up, I have tested with another methods and I didn't get the speedup I wished for, but it worth a try for this :)

**Comment by Uxio0** [comment]
This should be fixed when caching of prices was implemented
