### ISSUE TITLE
Refactor of Relay and Transaction services

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-relay-service#122]
For more info see #105

Currently, for Safes there are 2 ways of retrieving transactions:
- Using the **Relay Service**:
  - Txs sent using the relay server
  - Txs automatically indexed using tracing
- Using the **Transaction Service**:
  - Txs sent by any user but posted to this service. Confirmation txs can also be sent.

Having all this split have some problems: logic duplication (even if using common libraries), different endpoints... So a refactor would be desired.

**Relay Service**
=============
- Just keep transactions sent via the Relay Service, with all the parameters to `execTransaction` https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L78, as we are currently doing. I would like to have the txs just in the `Transaction Service` but will be slow to query that service for some checks (for example, current nonce). It will be redundant and `Transaction Service` should be the reference for storing/retrieving info of transactions, but at least for a first refactor we should keep it.
- Txs sent will be posted to the `Transaction Service`. They will be auto indexed either way, but this way we can have it before as `pending`.
- Remove tracing.

**Transaction Service**:
=====================
- Move all the implemented tracing logic to this Service (internal txs/ERC20/ERC721).
- Every Safe will be indexed automatically using the `ProxyCreation` event https://github.com/gnosis/safe-contracts/blob/5a8b07326faf30c644361c9d690d57dbeb838698/contracts/proxies/ProxyFactory.sol#L9. New proxies must be checked for the `implementation` address to be pointed to a known Gnosis Safe `master copy` address. Old Safes will be added via script or administrative command. As an idea for the future, it would be desirable to listen to `changeMasterCopy` method to prevent Proxies change to a non Gnosis Safe address.
- All the calls to `execTransaction` and `approveHash` will be decoded and stored as `SafeTx` or `SafeTxConfirmation`.
- Safe txs can still be posted to the service, that would be the only way to know the tx that generates a `safe tx hash` used in `approveHash`. If not posted, we will auto index the tx as long as `execTransaction` is called and tx is decoded.
- Confirmations of Safe txs can also be posted to the service with the `tx hash`, `safe tx hash` and the `owner`, but as we trust the client when the internal txs are available tx will be checked. We could decode the tx, but it would be problematic in the case that one of the owners is a contract doing more stuff in the call. For Externally Owned Accounts, it should be very straight forward, so we will try to decode.

**Comment by Uxio0** [comment]
What do you think @tschubotz @denisgranha @rmeissner?

**Comment by tschubotz** [comment]
Just after reading through this, this sounds like a good idea. Mainly to clean up code and remove logic duplication.
However, I would defer to what Denis and Richard think since they know more about the technical internals. :)

**Comment by rmeissner** [comment]
Looks good ... and sounds like some work :D

**Comment by tschubotz** [comment]
_from services sync_
- For the Team Safe, couldn't we have an endpoint to store confirmations?
- Once all confirmations are there, the tx can be executed.
- It would be waay nicer for UX.
- Are there any security concerns? 
- It would save gas as not on-chain confirmation is required.
- Are there issues with smart contracts as owners? Not if they implement EIP712 and contract signatures. The Safe does. 
- In the current solution, all confirmations are on-chain, so everyone would see it. Only the tx has, not the actual transaction data. The data is only on the service, in both cases.

@Uxio0 does some research and start with this and we'll check in more details when Richard is back.
