### ISSUE TITLE
Allow sponsored transactions

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-relay-service#126]
#### V1
- Transactions to pre-defined addresses should be for free
  - We need to check nested transactions in case of **Batched Transactions** (MultiSend) and if all targets in the batched transactions are whitelisted the transaction should be free
#### V2
- We should keep track on how many transactions for what gas prices where sponsored

#### V1
- Allow Sight to use sponsor transactions for Safe users that use Contract Proxy Kit
#### V2
- Allow partners to sponsor transactions for their users

## When is it needed
- Sight wants to start using sponsored batched transactions when integrating the Contract Proxy Kit

**Comment by tschubotz** [comment]
@tschubotz create epic?

**Comment by rmeissner** [comment]
@tschubotz bump ;)

**Comment by rmeissner** [comment]
How to prevent spam?
