### ISSUE TITLE
Use asynchronous queue for sending and retrying Safe transactions

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-relay-service#130]
Currently, txs are sent in a synchronous way. Client calls the service, it sends the tx to the node and returns the `txHash`, so client can follow up the mining process in another explorers like etherscan.io. Problem appears when there are problems mining the tx (network did not process or discarded it, gas prices increase just after tx is sent, reorgs...).

A first fix could be a periodical task checking the txs not mined after some time and resend then again using a higher `gasPrice`, but `txHash` will change.

The proposal would be that the client receives the `safeTxHash`, which will be the same not depending on the order relay sends the txs or even if the relay decides to resend it with a new `gasPrice`, and then the client can query the service for the tx to get the `txHash`

Process will be:
1. Client -> `POST /safes/<safe-address>/transactions` -> Returns `safeTxHash`
2. Tx should be sent almost instantaneously
3. Client -> `GET /safes/<safe-address>/transactions/<safeTxhash>` -> Returns `txHash`
4. A process will check `pending` txs every half a minute:
    - If tx is mined, and status is OK, a push notification is sent with `txMined` event and return `status` of the tx and maybe another useful data (like `gasUsed`).
    - If a tx has not been processed after a number of minutes (let's say 30 minutes), tx is submitted again with current standard `gasPrice` and relay will send new push notification `txHashChanged` to the clients.

An alternative to that process would be on point one:
1. Client -> `POST /safes/<safe-address>/transactions` -> Returns `safeTxHash` and `txHash`
Tx is sent synchronously so we already have `txHash` available at this point and it would make migration easier, but I would prefer to use the async proposal.

**Comment by Uxio0** [comment]
@rmeissner @denisgranha @tschubotz What do you think?

**Comment by denisgranha** [comment]
I think either we do this, or we should allow option to define gas price priority and split the submission through different accounts so transactions cannot be stucked or wait other from performing txs.

Something like:
3 queues each with one account for low, standard and fast
Each queue as soon as it gets N tx pending should use another account so nonces do not affect following txs

**Comment by rmeissner** [comment]
For me both solutions (async + multiple submitters) have different use casss and at some point we might have both.

I like the idea of returning an id instead of the hash and that can be used to query the state. This is also in line with our transactions list endpoint. There each tx also has an id.

Problem here is that dapps expect a transaction hash. There are different approaches which we need to discuss.

For the multiple gas case we need to check how we handle it if multiple transactions are submitted to the different speeds at the same time (first to slow, second to standard, third to fast)

**Comment by denisgranha** [comment]
yep good point, I wouldn’t allow changing the gas price if there are pending txs

**Comment by rmeissner** [comment]
See #264
