### ISSUE TITLE
Add tokens 

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#135]
While checking the stats, I found the following tokens that I think are worth adding since users send them to the Safe and there seems at least some volume on etherscan:

TrueUSD:
- https://etherscan.io/token/0x0000000000085d4780B73119b644AE5ecd22b376

ERC20:
- https://etherscan.io/token/0xc3761EB917CD790B30dAD99f6Cc5b4Ff93C4F9eA

DAY:
- https://etherscan.io/token/0xE814aeE960a85208C3dB542C53E7D4a6C8D5f60F

BOOTY:
- https://etherscan.io/token/0x6B01c3170ae1EFEBEe1a3159172CB3F7A5ECf9E5

ALIS:
- https://etherscan.io/token/0xEA610B1153477720748DC13ED378003941d84fAB

WSKR:
- https://etherscan.io/token/0x175666d12fC722aBD9E4a8EbF5d9B2d17b36B268

DPP:
- https://etherscan.io/token/0x01b3Ec4aAe1B8729529BEB4965F27d008788B0EB

CAN:
- https://etherscan.io/token/0x1d462414fe14cf489c7A21CaC78509f4bF8CD7c0

IDEX:
- https://etherscan.io/token/0xB705268213D593B8FD88d3FDEFF93AFF5CbDcfAE

SPANK: 
- https://etherscan.io/token/0x42d6622deCe394b54999Fbd73D108123806f6a18

I didn't find nice icons for all of them, so would just add without an icon.

**Comment by Uxio0** [comment]
Added!
