### ISSUE TITLE
Transaction cost exceeds current gas limit

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-relay-service#136]
I have discovered today in the logs that someone is trying to send a transaction that exceeds current block gas limit. Estimation is ok, but then when tx is sent we get a `Transaction cost exceeds current gas limit`.

It's a situation I have not foreseen, so it returns a 500 on the backend. I will deploy a patch soon that will return the error instead of a 500 (as we do with another errors), but we need to discuss what to do in case this situation arises again:

- Option 1. We check the current block gas limit and we return an error when doing the estimation if gas estimated it's bigger than the gas limit.
- Option 2. We just show the user the error when trying to send a tx.

@tschubotz @DmitryBespalov @rmeissner @germartinez @sche What do you think?

**Comment by rmeissner** [comment]
I vote for option 1. I think we should align in general how we report error to allow the clients to show more meaningful error message (an error code would make sense for me or we send a language header and the backend returns localized error messages).

**Comment by DmitryBespalov** [comment]
#1 I think is a good option - check + notify if an error occurred. We'll show the error to the user.

**Comment by tschubotz** [comment]
Option 1 `+1`

**Comment by Uxio0** [comment]
Ok! Current approach for errors is returning a json with `exception` and the `reason`. For example, when trying to execute a tx with a bad `safeNonce`:

```json
{
  "exception": "SafeMultisigTxExists: Tx with nonce=0 for safe=0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7 already exists in DB"
}```

Then, from that, some solutions:

1. Backend is integrated with lokalise (from what I read it's a little tedious, but doable), so I just return what clients must show depending on the languate they send in HTTP Headers.

```json
{
  "message":  "Nonce 0 ist veraltet for Safe 0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7, bitte neu einschätzen",
  "exception": "SafeMultisigTxExists: Tx with nonce=0 for safe=0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7 already exists in DB"
}```

2. I return an `errorCode` with an `arguments` param so clients know what to render. I would always leave the original exception in english because it's really useful for testing or for people using the API without app:

```json
{
  "errorCode":  26,
  "arguments": [0, "0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7"],
  "exception": "SafeMultisigTxExists: Tx with nonce=0 for safe=0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7 already exists in DB"
}```

**Comment by rmeissner** [comment]
I would slightly prefer 2. We just need to make sure to properly document errorCode to arguments :D (should be a unique mapping, right?)

Or we do both 🤔 
For 1. how would it look if we request a language that the backend doesn't support? Would `message` be `null` in this case? I would like to have a way to detect that we display the user a different language than he expects. Also for this I would say that we send the language we use as a display language as a http header (not the device language, difference for me is that the device might be in a language that we don'T support and on Android the system chooses one of the supported languages that fits the best ... most of the time english).

**Comment by Uxio0** [comment]
I would prefer 2, as devices have already implemented lokalise, we can have a spreadsheet with everything documented in english and the possible arguments.

I'm thinking it could even be better if we use an object instead of a list. That way, if I want to send you more data it will be easier and it will not break any client. Same happens for language that have different sentence construction:

```json
{
  "errorCode":  26,
  "arguments": {'nonce': 0, 'safe': "0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7"},
  "exception": "SafeMultisigTxExists: Tx with nonce=0 for safe=0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7 already exists in DB"
}
```

Maybe in the future it could evolve to:
```json
{
  "errorCode":  26,
  "arguments": {'nonce': 0, 'safe': "0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7", "expectedNonce": 8},
  "exception": "SafeMultisigTxExists: Tx with nonce=0 for safe=0x0A3C70d6a02188373B0DeA9C6c75B5d0fA7Ff1b7 already exists in DB"
}
```

In the case we do 1:
- Backend can always fallback to english.
- Backend sends `message: null`. This is my preferred.

As I'm counting on using http headers for language, I was expecting to use the standard to set multiple languages and the preference https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language, so you can always set English as fallback.

Backend will answer with `Content-Language` header so you know if you got the language you wanted

**Comment by Uxio0** [comment]
This is being discussed for the new verions already
