### ISSUE TITLE
Add BKN and XD token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#140]
Could you please add the following 2 tokens to our list? 

BKN: `0xBeE6EDF5fa7e862ed2eA9b9f42cb0849184aAE85`
(With logo please, info can be found here: https://github.com/MyEtherWallet/ethereum-lists/pull/1211/commits/ae0b826b52168b31950fae06200317e50cd3c837)

XD: `0x24dcc881e7dd730546834452f21872d5cb4b5293`

**Comment by Uxio0** [comment]
Done!

https://safe-relay.gnosis.pm/api/v1/tokens/?search=BKN
https://safe-relay.gnosis.pm/api/v1/tokens/?search=Data%20Transaction%20Token
