### ISSUE TITLE
Another week, more tokens

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#142]
Could you please add the following tokens:

https://etherscan.io/token/0xB6eD7644C69416d67B522e20bC294A9a9B405B31
https://etherscan.io/token/0x9e3319636e2126e3c0bc9e3134AEC5e1508A46c7
https://etherscan.io/token/0xA2dcA1505b07e39F96Ce41E875b447F46D50C6fc
https://etherscan.io/token/0x26946adA5eCb57f3A1F91605050Ce45c482C9Eb1

**Comment by Uxio0** [comment]
Done @tschubotz 

https://safe-relay.gnosis.pm/api/v1/tokens/0xB6eD7644C69416d67B522e20bC294A9a9B405B31
https://safe-relay.gnosis.pm/api/v1/tokens/0x9e3319636e2126e3c0bc9e3134AEC5e1508A46c7
https://safe-relay.gnosis.pm/api/v1/tokens/0xA2dcA1505b07e39F96Ce41E875b447F46D50C6fc
https://safe-relay.gnosis.pm/api/v1/tokens/0x26946adA5eCb57f3A1F91605050Ce45c482C9Eb1
