### ISSUE TITLE
PUT /v2/safes/{address}/funded/ - returned 404 error for safe with enough balance to deploy

### ISSUE THREAD

**Issue by sche** [gnosis/safe-relay-service#146]
We got an error report that safe deployment failed on iOS. After a deeper look, we figured out that it happened because relay service returned us 404 error on ```PUT /v2/safes/{address}/funded/``` call.
Please check production logs on date 03.07 from 15:38 to 15:42.
Please get in touch for more info.

**Comment by Uxio0** [comment]
V2 Funded was called for a safe created using the V1 endpoints. I guess it was someone who created it some time ago and tried to deploy it when the app was updated
