### ISSUE TITLE
Make services available for Goerli

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-relay-service#150]
It would be nice to make the services available on Goerli or provide an easy step-by-step instructions how to setup your own services. This should include all firebase setup + notifications service and maybe some references to the clients.

**Comment by Uxio0** [comment]
Documentation for setting up services for Goerli (or even Kovan, Ropsten, private network...) have been added to readthedocs:

- https://gnosis-safe.readthedocs.io/en/latest/services/transactions.html#setup
- https://gnosis-safe.readthedocs.io/en/latest/services/relay.html#setup
