### ISSUE TITLE
Token icon links on Rinkeby seem to be broken

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#153]
The URLs of the icons of the following tokens on *Rinkeby* seem to be broken. I get an access denied from AWS
- https://safe-relay.rinkeby.gnosis.pm/api/v1/tokens/?search=LOVE
- https://safe-relay.rinkeby.gnosis.pm/api/v1/tokens/?search=DAIc

![image](https://user-images.githubusercontent.com/1380529/65958903-d5620c00-e450-11e9-97e7-65648310956e.png)

**Comment by Uxio0** [comment]
Hi @tschubotz ,

It's fixed now, I configured icons for both tokens
