### ISSUE TITLE
Add Maharlika tokens

### ISSUE THREAD

**Issue by superern** [gnosis/safe-relay-service#155]
Coin
address: 0xE3D0a162fCc5c02C9448274D7C58E18e1811385f
logo: https://drive.google.com/file/d/1ryp8NgLQcIBu0bWA5s_DhBuPLBGXeWCg/view?usp=sharing
name: Maharlika Coin
description: The World's First Resource-Based Economy Cryptocurrency Advocating A Dividend System For Humanity
symbol: MHLK
decimals: 2
website: https://www.maharlikacoin.com
https://etherscan.io/token/0xE3D0a162fCc5c02C9448274D7C58E18e1811385f

Asset
address: 0xdb141cbace1aa23a0858e14ace38060734f63fb5
logo: https://drive.google.com/file/d/1ryp8NgLQcIBu0bWA5s_DhBuPLBGXeWCg/view?usp=sharing
name: Maharlika Asset
description: The World's First Resource-Based Economy Cryptocurrency Advocating A Dividend System For Humanity
symbol: MHKC
decimals: not available
website: https://www.maharlikacoin.com
https://etherscan.io/token/0xdb141cbace1aa23a0858e14ace38060734f63fb5

**Comment by Uxio0** [comment]
The token has been added to the service, the asset has not because as @rmeissner said we currently don't provide support for ERC721 tokens.

https://safe-relay.gnosis.pm/api/v1/tokens/?search=Maharlika

**Comment by superern** [comment]
> The token has been added to the service, the asset has not because as @rmeissner said we currently don't provide support for ERC721 tokens.
> 
> https://safe-relay.gnosis.pm/api/v1/tokens/?search=Maharlika

Thank you.
