### ISSUE TITLE
Service does not support eth_sign signatures.

### ISSUE THREAD

**Issue by andrewdamelio** [gnosis/safe-relay-service#158]
When I hit the endpoint 
```https://safe-relay.rinkeby.gnosis.pm/api/v/safes/[address]/transactions/```
 using a signMessage transaction (instead of a signDigest) I'm getting the below error.

```
 {"signatures":{"0":{"v":["v should be 0, 1 or be in 27-28"]}}}
```

Based on this contract update, I expected this to work? Does the relayer need to be updated?
https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L264-L266

**Comment by rmeissner** [comment]
Development is not yet deployed to the networks and therefore not supported by the relay service right now. This will we added in the future.

**Comment by andrewdamelio** [comment]
This also fails for me when running```safe-relay-service``` locally -- does the current development code support this?

How can I go about getting support for this in my local build? Need to build against these new features 🙏

**Comment by Uxio0** [comment]
Current development code does not support this

**Comment by Uxio0** [comment]
@andrewdamelio I added a quick fix for it to run it locally, you can use the `issue-158` branch https://github.com/gnosis/safe-relay-service/tree/issue-158

**Comment by rmeissner** [comment]
We should check what types of signatures we want to support in the relay (I would only suggest EIP-712, eth_sign and on-chain signatures for now, the costs for EIP-1271 can vary quiet a lot which can be abused to drain the funds of our relay)

**Comment by Uxio0** [comment]
This feature is already in `develop` branch with the support of the new Safe V1.1.0 contracts 1c7b7a94974f527523f79ce944c02971d35b5256
