### ISSUE TITLE
Deprecate old create endpoints

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-relay-service#161]
At this point every client should be migrated to the new `v2` CREATE2 endpoints, so old endpoints should be deprecated to prevent people creating old v0.1.0 Safes. The endpoints to be deprecated are:

- `POST /v1/safes/`
- `POST /v1/safes/estimate/`
- `PUT /v1/safes/{address}/funded/`

What do you think @tschubotz @rmeissner @DmitryBespalov?

**Comment by rmeissner** [comment]
do you have any stats on usage?

**Comment by Uxio0** [comment]
@rmeissner That endpoint has created:
- 1 Safe in November (Dima's testing one)
- No Safes in October
- 1 in September
- 6 in August
- 1 in July
- 54 in June
- 115 in May

I would say there's no risk on deprecating the endpoint in next version

**Comment by DmitryBespalov** [comment]
I would say I don't really know if the people who created safes with old endpoints have upgraded to the new app version. Maybe they still have the safe but did not actually use it and it sits on their phone. 

I would be careful with our users on that side. I'd propose to send out a push notification and or write a blog post that we are deprecating old versions and people are encouraged to update to ta new version.

**Comment by Uxio0** [comment]
@DmitryBespalov This change would just affect people creating new safes, not for doing txs with old safes. I think it has been enough time to update the apps to the new versions. In my opinion we should just deprecate the endpoints and not make a big deal of that
