### ISSUE TITLE
Ability to specify the `data` and `to` params in safe creation request

### ISSUE THREAD

**Issue by nuevoalex** [gnosis/safe-relay-service#163]
## Context / issue

Currently the API does not support the ability to specify the `data` and `to` params.

## Proposed solution

We would like the ability to specify the `data` and `to` params for safe creation setup when requesting a safe be created through the relay API.

## Additional context

This is fairly key to the user flow for our application as it ensures that if the safe gets created at all we'll have a persistent reference to the safe address that can't possibly be lost and is easily retrievable across environments.

**Comment by Uxio0** [comment]
Hi @nuevoalex, we don't have it in the roadmap as we currently don't need it and it increases uncertainty in the deployment of a new Safe (e.g. anyone could add a module or change the owners), but it would be possible to have it implemented and enabled/disabled in the application settings

**Comment by nuevoalex** [comment]
Thanks! Out of curiosity in which context are you concerned about a malicious party using this to unexpectedly modify the safe?

There’s a case we’re concerned about but we believe it’s remedied by doing 2 things: 
Off chain: confirming the create2 address using the expected params returned by the relay
On chain: confirming the address matches expected create2 value for the setup params that should have been used for a user (made a separate issue for this in contracts as we’d need the payment value to do this)

**Comment by Uxio0** [comment]
> Thanks! Out of curiosity in which context are you concerned about a malicious party using this to unexpectedly modify the safe?
Having to check the code that is going to be executed when the Safe is deployed, as it would allow anyone to change variables on the Safe

> There’s a case we’re concerned about but we believe it’s remedied by doing 2 things:
> Off chain: confirming the create2 address using the expected params returned by the relay
> On chain: confirming the address matches expected create2 value for the setup params that should have been used for a user (made a separate issue for this in contracts as we’d need the payment value to do this)
We are doing both on our clients, but that won't cover checking that the code you are running is not malicious
