### ISSUE TITLE
Add support for MCD DAI

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#166]
**Context**
Maker is transitioning to multi collateral DAI. We shoul support old and new in parallel until we deprecate SAI (single collateral DAI).

**Tasks**
- Please add (MCD) DAI to our token list: https://etherscan.io/token/0x6B175474E89094C44Da98b954EedeAC495271d0F (The token symbol should be DAI, same like etherscan does it)
- Please also enable this as payment token.
- Icon image assets can be found here: https://www.notion.so/Maker-Brand-ac517c82ff9a43089d0db5bb2ee045a4

- Please rename the old DAI to SAI (cf. how etherscan did it: https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359?a=0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359)
- Please leave this one as payment tokens as well until we deprecate it in the future.

**Comment by Uxio0** [comment]
Done:

- https://safe-relay.gnosis.pm/api/v1/tokens/?search=Dai%20Stablecoin
- https://safe-relay.gnosis.pm/api/v1/tokens/?search=SAI
