### ISSUE TITLE
Add Rinkeby tokens for the dfusion team

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#169]
Following up from https://gnosisinc.slack.com/archives/C63LQTGNB/p1574679029011400. Please add the following tokens to our Rinkeby token list:

```
OWL - 0xa7d1c04faf998f9161fc9f800a99a809b84cfc9d
```
All tokens from:
https://raw.githubusercontent.com/gnosis/dex-react/develop/src/api/tokenList/tokenList.json

cc @bh2smith

**Comment by bh2smith** [comment]
And to make your lives easier, I have extracted the relevant addresses out of the token list for yah!

```
USDT - 0xa9881E6459CA05d7D7C95374463928369cD7a90C
TUSD - 0x0000000000085d4780B73119b644AE5ecd22b376
USDC - 0x4DBCdF9B62e891a7cec5A2568C3F4FAF9E8Abe2b
PAX  - 0xBD6A9921504fae42EaD2024F43305A8ED3890F6f
GUSD - 0x784B46A4331f5c7C495F296AE700652265ab2fC6
```

Assuming that WETH and DAI (0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa) are already listed.
