### ISSUE TITLE
Rename cSAI, add new cDAI

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#170]
Please rename our existing cDAI to cSAI (single collateral dai).

Please add new new MCD cDAI (https://etherscan.io/address/0x5d3a536e4d6dbd6114cc1ead35777bab948e3643)

Token assets can be found at https://drive.google.com/drive/u/0/folders/1UhTswCEgzsokHQKLnTv4kyxhU70V9Wxm

**Comment by Uxio0** [comment]
I renamed cDAI to cSAI and added the new MCD cDAI, I will change the images on monday :)

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/0x5d3a536e4d6dbd6114cc1ead35777bab948e3643/
https://safe-relay.gnosis.io/api/v1/tokens/0xF5DCe57282A584D2746FaF1593d3121Fcac444dC/
