### ISSUE TITLE
Add CHAI token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#171]
Please add the CHAI token to our token list (https://etherscan.io/token/0x06af07097c9eeb7fd685c692751d5c66db49c215)

The icon can probably be taken from https://chai.money/

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/0x06AF07097C9Eeb7fD685c692751D5C66dB49c215/
