### ISSUE TITLE
Exception: InvalidGasEstimation - sometimes happens

### ISSUE THREAD

**Issue by sche** [gnosis/safe-relay-service#178]
Here is the linked issue: https://github.com/gnosis/safe-ios/issues/1376
```
2019-12-16 10:04:14,249 [WARNING] [MainProcess] https://safe-relay.gnosis.io/api/v1/safes/0xFB1d445c27A860bb6330453Bf08254198F3E0E31/transactions/ - Exception: InvalidGasEstimation: Gas should be at least equal to safe-tx-gas=328052 and data-gas=70492. Current is safe-tx-gas=327812 and data-gas=70428
```

**Comment by Uxio0** [comment]
Hi @sche. When I tx is sent relay checks that the gas is enought for the execution of the transaction. Minimum values are the ones that are calculated in the `estimate` endpoint. It could by happening by some reasons:
- Tx is estimated, but when it's executed the estimation is different. E.g. Tx for sending ERC20 is estimated, the person you want to send the ERC20 sends all his ERC20 token, so you know have to pay for initializing the storage and it's not enough when you try to send the Safe tx.
- Estimated `safeTxGas` and `baseGas` are messed up from estimation to posting the tx to the service.

I checked the service and seemed to be alright, if not the txs will never be sent
