### ISSUE TITLE
Enable "gzip" for /v1/tokens/ endpoint

### ISSUE THREAD

**Issue by DmitryBespalov** [gnosis/safe-relay-service#179]
As part of https://github.com/gnosis/safe/issues/251, we need to test how archived HTTP response on the /tokens/ endpoint works with the clients (iOS, Android) when the token size is ~2000 tokens.

Please enable archiving of responses for that endpoint 😄

**Comment by Uxio0** [comment]
Hi @DmitryBespalov, gzip should be already enabled, I have just tested on Dev, Staging and Production and it's returning a gzip in the `tokens` endpoint.
