### ISSUE TITLE
Add Nexusmutual Token

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-relay-service#181]
Please add the Nexusmutual (NXM) token.

Token address: 0xd7c49CEE7E9188cCa6AD8FF264C1DA2e69D4Cf3B
Logo: https://pbs.twimg.com/profile_images/1004666585292951554/WPfTLP3M.jpg

Also it appears that the SNX logo doesn't have a logo yet. We could use this one: https://miro.medium.com/max/566/0*7d10sZlON6k5FbAP

**Comment by Uxio0** [comment]
Done https://safe-relay.gnosis.io/api/v1/tokens/0xd7c49CEE7E9188cCa6AD8FF264C1DA2e69D4Cf3B/
