### ISSUE TITLE
Add MOD Token

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-relay-service#189]
Please add the Modum (MOD) token to our token list (https://etherscan.io/token/0x957c30aB0426e0C93CD8241E2c60392d08c6aC8e)

The icon can be taken from https://s2.coinmarketcap.com/static/img/coins/200x200/2080.png?_=6f9d24a

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/0x957c30aB0426e0C93CD8241E2c60392d08c6aC8e/
