### ISSUE TITLE
transactions with custom gasPrice

### ISSUE THREAD

**Issue by andrewdamelio** [gnosis/safe-relay-service#190]
Question

I'm trying to use the ```safes/<str:address>/transactions/``` Relay API end point and i'm providing a gasPrice to use but it seems like the relayer uses its own internal gasEstimate for standard -- maybe i'm missing something but is it possible to have the relayer use the provided gasPrice?

```
    def _get_configured_gas_price(self) -> int:
        """
        :return: Gas price for txs
        """
        return self.gas_station.get_gas_prices().standard
```

**Comment by Uxio0** [comment]
Hi @andrewdamelio,

We currently don't allow that as we share the same address for sending all the client transactions. If you are able to set the `gasPrice` yourself you a malicious user could configure a very low `gasPrice` and get all the next transactions stuck

**Comment by andrewdamelio** [comment]
@Uxio0 Thanks for the response!

any reason gasPrice is accepted as a parameter on the actually API call if it isn't used? Does it serve another purpose.

**Comment by Uxio0** [comment]
@andrewdamelio You are welcome!

That `gasPrice` is the one from the inner tx: https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L114

It's used to estimate the refund the Safe has to pay back to the relayer

**Comment by joeykrug** [comment]
Hmmm, what about for users who want to use the gas prices on the relay gas estimator? Like safeLow, standard, and fast? Could we allow them to pass those 3 (which the safe already has)?

**Comment by joeykrug** [comment]
At the very least, users will want to / need to be able to use gas prices *above* the standard one, which I don't see a problem with?

As is, I could still clog a relayer up by doing a bunch of high gas transactions with the standard price which may not ever go through..

**Comment by Uxio0** [comment]
> As is, I could still clog a relayer up by doing a bunch of high gas transactions with the standard price which may not ever go through..

**Comment by Uxio0** [comment]
> Hmmm, what about for users who want to use the gas prices on the relay gas estimator? Like safeLow, standard, and fast? Could we allow them to pass those 3 (which the safe already has)?

Sorry, I didn't understand that question

> As is, I could still clog a relayer up by doing a bunch of high gas transactions with the standard price which may not ever go through..

Well, we accept everything above `safeLow` but will always use `standard` when sending the tx, even if the relay is making a loss. `standard` should guarantee that txs will go through, at least in our experience is really weird for txs to be stuck more than a few minutes

**Comment by joeykrug** [comment]
We want the ability to pass in a gas price of `x`, have the relayer relay the transaction with that gas price of `x`, and have the refund be based on a gas price of `x`. Where `x` is a number >= safeLow, or if you're worried about malicious users, where `x` is a number >= standard.

Does that make sense?

**Comment by Uxio0** [comment]
> We want the ability to pass in a gas price of x, have the relayer relay / actually send the transaction with that gas price of x, and have the refund be based on a gas price of x. Where x is a number >= safeLow, or if you're worried about malicious users, where x is a number >= standard.

So you want to be able a higher `gasPrice` so your transaction is guaranteed not to be stuck. That's possible, but the problem I see if that you depend on all the transactions other users sent before you, so if their transactions are not mined yours won't be either

**Comment by joeykrug** [comment]
> So you want to be able to set a higher gasPrice so your transaction is guaranteed not to be stuck.

Yes

> That's possible, but the problem I see is that you depend on all the transactions other users sent before you, so if their transactions are not mined yours won't be either

Why is this? How do I depend on all the transactions other users sent before me? Does the gnosis relay only relay transactions one at a time, like it does them sequentially and can't have multiple pending at once?

**Comment by Uxio0** [comment]
> Why is this? How do I depend on all the transactions other users sent before me? Does the gnosis relay only relay transactions one at a time, like it does them sequentially and can't have multiple pending at once?

Because currently we just use one sender account. Having multiple sender accounts would require to have ether in different accounts and balance txs between them, that's something we discuss but it doesn't seem to be needed at our current level of use of the relay, but it might change if we have more users.

There are multiple pending txs, every one from the same account with increasing nonce, we don't relay one by one, usually multiple txs are included in the same block (depending on gas usage, of course).
