### ISSUE TITLE
Add Aave "aTokens"

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-relay-service#196]
Add the following tokens:

aETH 0x3a3a65aab0dd2a17e3f1947ba16138cd37d08c04
aDAI 0xfC1E690f61EFd961294b3e1Ce3313fBD8aa4f85d
aUSDC 0x9ba00d6856a4edf4665bca2c2309936572473b7e
aSUSD 0x625ae63000f46200499120b906716420bd059240
aTUSD 0x4da9b813057d04baef4e5800e36083717b4a0341
aUSDT 0x71fc860F7D3A592A4a98740e39dB31d25db65ae8
aBAT 0xe1ba0fb44ccb0d11b80f92f4f8ed94ca3ff51d00
aKNC 0x9d91be44c06d373a8a226e1f3b146956083803eb
aLEND 0x7D2D3688Df45Ce7C552E19c27e007673da9204B8
aLINK 0xA64BD6C70Cb9051F6A9ba1F163Fdc07E0DfB5F84
aMANA 0x6FCE4A401B6B80ACe52baAefE4421Bd188e76F6f
aMKR 0x7deb5e830be29f91e298ba5ff1356bb7f8146998
aREP 0x71010a9d003445ac60c4e6a7017c1e89a477b438
aSNX 0x328c4c80bc7aca0834db37e6600a6c49e12da4de
aWBTC 0xfc4b8ed459e00e5400be803a9bb3954234fd50e3
aZRX 0x6Fb0855c404E09c47C3fBCA25f08d4E41f9F062f

Here's the logos
![aBAT@2x](https://user-images.githubusercontent.com/17196842/73615091-66b2dc00-4605-11ea-8b8b-3aa56acf34e7.png)
![aDAI@2x](https://user-images.githubusercontent.com/17196842/73615092-66b2dc00-4605-11ea-8e7b-5204edc41e2f.png)
![aETH@2x](https://user-images.githubusercontent.com/17196842/73615093-674b7280-4605-11ea-86bd-041010155734.png)
![aKNC@2x](https://user-images.githubusercontent.com/17196842/73615094-674b7280-4605-11ea-8c35-99a9a2a69836.png)
![aLEND@2x](https://user-images.githubusercontent.com/17196842/73615095-674b7280-4605-11ea-899b-10ad96517ddc.png)
![aLINK@2x](https://user-images.githubusercontent.com/17196842/73615096-67e40900-4605-11ea-9b02-b44631a9d4b4.png)
![aMANA@2x](https://user-images.githubusercontent.com/17196842/73615097-67e40900-4605-11ea-9c99-abae7d2a6948.png)
![aMKR@2x](https://user-images.githubusercontent.com/17196842/73615098-67e40900-4605-11ea-9300-26f6d26c65a6.png)
![aREP@2x](https://user-images.githubusercontent.com/17196842/73615099-67e40900-4605-11ea-904b-9d8fd7cab500.png)
![aSNX@2x](https://user-images.githubusercontent.com/17196842/73615100-67e40900-4605-11ea-90d6-f8d37ce2bc8a.png)
![aSUSD@2x](https://user-images.githubusercontent.com/17196842/73615101-687c9f80-4605-11ea-8aa7-893958a2b419.png)
![aTUSD@2x](https://user-images.githubusercontent.com/17196842/73615102-687c9f80-4605-11ea-864c-112f30866979.png)
![aUSDC@2x](https://user-images.githubusercontent.com/17196842/73615103-687c9f80-4605-11ea-943c-8aab256071af.png)
![aUSDT@2x](https://user-images.githubusercontent.com/17196842/73615104-687c9f80-4605-11ea-9022-45fb3570a849.png)
![aWBTC@2x](https://user-images.githubusercontent.com/17196842/73615105-69153600-4605-11ea-8fa7-b7f20ff3e7be.png)
![aZRX@2x](https://user-images.githubusercontent.com/17196842/73615106-69153600-4605-11ea-9744-bbe19a55688b.png)

**Comment by rmeissner** [comment]
While to some extent self explanatory it would have been nice to sort the images together with the addresses ;)

**Comment by lukasschor** [comment]
Files have the same names as the tokens. (Also sent them to Uxio via Slack)

**Comment by rmeissner** [comment]
Hmm ok nvm then, was not visible on mobile ... There files had cryptic names :/

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/?search=Aave
