### ISSUE TITLE
Gas cost changes for IO-heavy operations

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-relay-service#200]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-150.md

**Comment by rmeissner** [comment]
This issue still exists

https://etherscan.io/tx/0x19d5907ebfcd3fc8640b2e7c042c7f2c34be5fec12a2fa9283bd5dccbb8604e9

**Comment by rmeissner** [comment]
@rmeissner add some steps to reproduce

**Comment by Uxio0** [comment]
@koeppelmann @rmeissner A fix for this has just been deployed to production, let's see if it works
