### ISSUE TITLE
Add Realt tokens

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-relay-service#203]
Add RealTokens.

Name: **RealToken (Audubon)**
Symbol: AUDUBON
Contract: 0x43688910273f199b8ae2ca018c13918fb3d37b58

Name: **RealToken (Patton)**
Symbol: PATTON
Contract: 0xeD42CeDcADbFbCAA3E6F411B09567C2C0b5AD28F

Name: **RealToken (Fullerton)**
Symbol: FULLERTON
Contract: 0x22c8ecf727c23422f47093b562ec53c139805301

Name: **RealToken (Marlowe)**
Symbol: MARLOWE
Contract: 0xe5f7ef61443fc36ae040650aa585b0395aef77c8

Use the same icon for all of them:
![image](https://user-images.githubusercontent.com/17196842/74612030-b6af9980-5101-11ea-8c3f-05203a05ee13.png)

**Comment by Uxio0** [comment]
@lukasschor It will take a little longer than the other tokens, as SYMBOL is too long and I have to do a migration on DB

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/?search=RealToken

**Comment by lukasschor** [comment]
![image](https://user-images.githubusercontent.com/17196842/74653738-156c2600-5189-11ea-8b29-7f4fc4ff68b5.png)

The default names/symbols are breaking the UI. Could we use the names provided above instead?

**Comment by Uxio0** [comment]
Done @lukasschor, close the issue if it's ok now :)

**Comment by lukasschor** [comment]
Nice. Thanks!
