### ISSUE TITLE
Add PAN token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#206]
Please add the PAN token to our token list

https://etherscan.io/token/0xD56daC73A4d6766464b38ec6D91eB45Ce7457c44

**Comment by Uxio0** [comment]
@tschubotz https://safe-relay.gnosis.io/api/v1/tokens/0xD56daC73A4d6766464b38ec6D91eB45Ce7457c44/

I used the logo in their webpage after some gimp :)

**Comment by porobov** [comment]
Already see it in the app! Fantastic!
