### ISSUE TITLE
Add Set tokens

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-relay-service#207]
Use the following logo for all tokens

![set-logo-icon-color-4x](https://user-images.githubusercontent.com/17196842/75224505-e832ff80-57a8-11ea-9288-d966d254f6f2.png)

Tokens (Name | Address)

ETH20SMACO | 0x9ea463Ec4cE9E9E5bc9cFd0187C4Ac3a70DD951D
ETH50SMACO | 0xa360F2aF3F957906468c0FD7526391AeD08aE3DB
ETH12EMACO | 0x2c5a9980B41861D91D30d0E0271d1c093452DcA5
ETH26EMACO | 0x614857c755739354d68ae0abd53849cf45d6a41d
ETHMINVOL | 0xF1E5F03086e1c0Ce55E54cd8146BC9c28435346F
ETHLOVOL | 0x585C2cF94c41b528ec7329CBc3cdE3C4f8d268dB
ETHHIVOL | 0x8Ddc86DbA7ad728012eFc460b8A168Aba60B403B
BTCHIVOL | 0x6123A0CBC95Cb157995A0795187A60995B85e0A9
BTCMINVOL | 0x81c55017F7Ce6E72451cEd49FF7bAB1e3DF64d0C
BTCLOVOL | 0x20649d97b1393105cf92a5083fd2afF7C99eBe56
BTCETH5050 | 0xc06aEc5191bE16b94FfC97B6Fc01393527367365
BTCETH7525 | 0xA35Fc5019C4dc509394Bd4d74591a0bF8852c195
ETHBTC7525 | 0xA6c040045d962e4B8eFa00954c7d23CCd0a2b8AD
ETHMACOAPY | 0xeF0fDA1d4bd73DDC2f93A4e46E2E5aDBC2D668f4
ETHEMAAPY | 0x316b13B951Efe25AAd1Cb565385B23869A7D4c48
ETHBTCRSI | 0xbf70A33A13fBe8D0106Df321Da0Cf654d2E9Ab50
ETHRSI6040 | 0x93E01899c10532d76C0E864537a1D26433dBbDdB
ETHRSIAPY | 0x136faE4333EA36A24bb751E2d505D6ca4Fd9f00b
ETHBTCEMACO | 0xB9FfE0b8Ee2d1Af94202FFED366520300748A4d8
iETH50SMACO | 0xAC1565e473F69FAdA09661A6B4103FBbF801CeEE
iETH20SMACO | 0x5cD487CE4dB7091292F2E914F7B31445Bd4A5E1b
ETHMOONX | 0x73104e9d3Da91e410A6c211068f7BFfabBbD3e26
ETHUSDADL4 | 0xB8243B4eeca27A4191e879760b88fE2270561796
INTETH | 0x7b8d9e95cAa85d7905c3435dA1bA9FA7f79bf4fA
BBB | 0x78E14B9A8D006eC7E23988a0A87263569c3F4839
BTCMOON | 0x09aE0c4c34A09875660E681FE1890F3b35175151
INTBTC | 0xd235e29B1dd177cd74F2955d081204A6cd04515e
GREED | 0x5958107be1Ecc8D0D1593b3d7cC75F5E48304682
BTCMOONX | 0x90f49083ff588ec5a5459F4D2A64B8D409C03122
EVOL | 0xaC6560DF686F3ac7039B0DD6867C874c99D9dA06
TLS | 0xdc5BBCF8189a69337f693A9f3F63Ae37789eDe92
FLEXETH | 0x8D66DF717FAF06c07b5D3E53FFD3eA66D612e150
ICHIEMA | 0xe86811516F9E46F6F2a8a19754c893deD414D682
FLEXBTC | 0xCf50bc1442A50D1756b34119fE1E26325Aa648e3
ETH10K | 0xAbC754aC2161B557D28062F41DcC0fc18440ac7E
FLEXETHBTC | 0xdBf5c7D8ac5007667617a15DB2c1B1D616c9D302
RIC (TON) | 0xb272422B7d07B94859AD61E4435c6d5087f308de
LONG | 0x28C6A58C2A5d8c5F6681e07bfa0AdA4bea14C9EE
BTCUSDCRSI | 0xe33A35fD5cad21cE72ebbC8a2885Bdd0983De043
BBE | 0x8C7C047051F37746BB1DCD16ae37851a3891635C
ETHUSDCTA | 0xD9c6d58eC4b6045067190042999351889fd27Eb7
BTCUSDCTA | 0x80AF3F06AefB9F436981cb12b9Da35c5dA023Efd
ETHSS | 0xDD7ae9466C9CaAD4bF632F796EAF4287F9616A7a
ETA | 0xaAa4eB35D08Dbb9b1B8760cb9fFE77b9023D7511

**Comment by Uxio0** [comment]
Done :)
