### ISSUE TITLE
Add Stablecoins

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-relay-service#214]
# USD Coin (USDC)
Address: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
Logo: https://s2.coinmarketcap.com/static/img/coins/200x200/3408.png

# Binance USD (BUSD)
Address: 0x4fabb145d64652a948d72533023f6e7a623c7c53
Logo: https://s2.coinmarketcap.com/static/img/coins/64x64/4687.png

# True USD (TUSD)
Address: 0x0000000000085d4780B73119b644AE5ecd22b376
Logo: https://images.prismic.io/dd-market-site-test%2F84bb13b2-23ef-4787-9e29-0898fd02fb36_tusd-500x500.svg?auto=compress,format

# True GBD (TGBD)
Address: 0x00000000441378008ea67f4284a57932b1c000a5
Logo: https://images.prismic.io/dd-market-site-test%2Faca639a4-54fd-44c7-81d1-82ab57ee199e_tgbp-500x500.svg?auto=compress,format

# True AUD (TAUD)
Address: 0x00006100F7090010005F1bd7aE6122c3C2CF0090
Logo: https://images.prismic.io/dd-market-site-test%2Fe03c9bd6-7c94-47bf-b939-1424e4305164_taud-500x500.svg?auto=compress,format

# True CAD (TCAD)
Address: 0x00000100F2A2bd000715001920eB70D229700085
Logo: https://images.prismic.io/dd-market-site-test%2F0d1f43e4-70f7-4e0f-b897-42dc51c74884_tcad-500x500.svg?auto=compress,format

# True HKD (THKD)
Address: 0x0000852600ceb001e08e00bc008be620d60031f2
Logo: https://images.prismic.io/dd-market-site-test/dd21bf88cef990bfd9751d6f09bf2eb787e096c7_thkd.png?auto=compress,format

# PAXOS (PAX)
Address already added (0x8e870d67f660d95d5be530380d0ec0bd388289e1)
Logo missing: https://s2.coinmarketcap.com/static/img/coins/200x200/3330.png

# Gemini Dollar (GUSD)
Address already added (0x056fd409e1d7a124bd7017459dfea2f387b6d5cd)
Logo missing: https://s2.coinmarketcap.com/static/img/coins/200x200/3306.png

**Comment by Uxio0** [comment]
Done @lukasschor :)
