### ISSUE TITLE
Decode Sight Operations

### ISSUE THREAD

**Issue by denisgranha** [gnosis/safe-relay-service#221]
Would be nice to have Conditional TOkens and SIght Market Operations decoded by the Safe relay so it's easier to confirm those transactions in the interface.

* ABI/ADDRESS for Conditional TOkens: https://unpkg.com/browse/@gnosis.pm/conditional-tokens-contracts@1.0.1/build/contracts/ConditionalTokens.json

* Market Maker Factory: https://unpkg.com/browse/@gnosis.pm/conditional-tokens-market-makers@1.8.1/build/contracts/LMSRMarketMakerFactory.json

* Market Maker Instance:  https://unpkg.com/browse/@gnosis.pm/conditional-tokens-market-makers@1.8.1/build/contracts/LMSRMarketMaker.json

**Comment by Uxio0** [comment]
Implemented in b18bd1b9b2d000e346e6e3178beb371b03313781
