### ISSUE TITLE
Add EWTB Token

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-relay-service#222]
Symbol: EWTB
Name: Energy Web Token Bridged
Token contract: 0x178c820f862b14f316509ec36b13123da19a6054 
Image: https://i.imgur.com/4NBgszl.png

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/0x178c820f862b14f316509ec36b13123da19a6054/
