### ISSUE TITLE
Add Compound Tether to mainnet token list

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#225]
Now that Compound has added Tether, we should add the Compound token to our token list: https://etherscan.io/token/0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9

I believe on Rinkeby we already have an icon for this token, otherwise it's here again: https://app.compound.finance/images/ctoken_usdt_product.svg

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9/
