### ISSUE TITLE
Add new Set token

### ISSUE THREAD

**Issue by lukasschor** [gnosis/safe-relay-service#228]
Name: LINKETH RSI Ratio Set
Ticker: LINKETHRSI
Token address: 0x8933ea1ce67b946bdf2436ce860ffbb53ce814d2
Image: Same as other Set tokens

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/0x8933ea1ce67b946bdf2436ce860ffbb53ce814d2/
