### ISSUE TITLE
Add GHOST token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#230]
Please add the following token to our token list on mainnet:

```
Project: Ghost
Contract: 0x4c327471c44b2dacd6e90525f9d629bd2e4f662c
Decimals: 18
Website: https://www.ghostbymcafee.com/
```

Icon:

![GHOST](https://user-images.githubusercontent.com/1380529/82795826-d549cd00-9e74-11ea-8217-7d05fd9ffde3.png)

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.io/api/v1/tokens/0x4c327471C44B2dacD6E90525f9D629bd2e4f662C/
