### ISSUE TITLE
Add new SNX token

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-relay-service#234]
The SNX token has been migrated 

see https://blog.synthetix.io/proxy-contract-cutover-on-may-10/

New address:
https://etherscan.io/address/0xc011a72400e58ecd99ee497cf89e3775d4bd732f

**Comment by Uxio0** [comment]
Hi, I've migrated SNX last week https://safe-relay.gnosis.io/api/v1/tokens/0xc011a72400e58ecd99ee497cf89e3775d4bd732f/
