### ISSUE TITLE
Add DIA token

### ISSUE THREAD

**Issue by kaythxbye** [gnosis/safe-relay-service#240]
Hey everyone!
We are building an open-source database for financial data with our DIA token and it would be great to have the token information in the gnosis service available. 
Our token address is: https://etherscan.io/token/0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419
Name is DIA
Icon is also on the Etherscan page.

I hope this is the correct channel to contact you.

**Comment by Uxio0** [comment]
Hi @kaythxbye. This is the correct channel. Etherscan icon is not enough as it's too small, do you have another one?

**Comment by kaythxbye** [comment]
Hi @Uxio0! Thanks for the heads up, here you can get a HQ version of our icon: https://diadata.org/wp-content/uploads/2020/06/dia.png

**Comment by Uxio0** [comment]
It has been added
