### ISSUE TITLE
Add XRT Token

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-relay-service#242]
Add XRT Token

Contract: 0x7de91b204c1c737bcee6f000aaa6569cf7061cb7
Name: Robonomics
Ticker: XRT
Logo: https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x7dE91B204C1C737bcEe6F000AAA6569Cf7061cb7/logo.png

**Comment by Uxio0** [comment]
Done
