### ISSUE TITLE
Add KRL token

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-relay-service#244]
Add KRL Token

Contract: 0x464ebe77c293e473b48cfe96ddcf88fcf7bfdac0
Name: Kryll
Ticker: KRL
Logo: https://s2.coinmarketcap.com/static/img/coins/64x64/2949.png

**Comment by icecube42** [comment]
[kryll_logo.zip](https://github.com/gnosis/safe-relay-service/files/4874190/kryll_logo.zip)

**Comment by icecube42** [comment]
Hi I  uploaded vectorial version maybe it's better :)   In your apps "Gnosis safe" the other logo are 64x64 version?

**Comment by Uxio0** [comment]
> Hi I uploaded vectorial version maybe it's better :) In your apps "Gnosis safe" the other logo are 64x64 version?

Thanks. No, we try to use at least 200x200 (I would use https://s2.coinmarketcap.com/static/img/coins/200x200/2949.png )

**Comment by Uxio0** [comment]
Done

**Comment by icecube42** [comment]
> Done

Thank you very much!!!!! 👏👏👏😎🥳
