### ISSUE TITLE
Add KARMA Token

### ISSUE THREAD

**Issue by sidko** [gnosis/safe-relay-service#248]
This for the KARMA Token from Andrew Lee of Karma DAO. 

Contract: 0xdfe691F37b6264a90Ff507EB359C45d55037951C
Decimals: 4
Image: https://roll-token.s3.amazonaws.com/KARMA/55c22dfd-f118-4204-a9a8-fdf64d323719

Let us know if you need any more details.

**Comment by Uxio0** [comment]
Done!
