### ISSUE TITLE
Add token "DFOHub - BUIDL"

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-relay-service#249]
**Token information**
- Name: DFOHub - BUIDL
- Etherscan link: https://etherscan.io/token/0x7b123f53421b1bF8533339BFBdc7C98aA94163db
- Website (to prevent scam tokens): https://www.dfohub.com/
- Image: ![image](https://user-images.githubusercontent.com/11056031/89169327-6082c580-d57e-11ea-9f68-e1a35b561b2c.png)

Additional context for validation: 
Old token uniswap.info: https://uniswap.info/token/0xD6F0Bb2A45110f819e908a915237D652Ac7c5AA8
New token uniswap.info: https://uniswap.info/token/0x7b123f53421b1bf8533339bfbdc7c98aa94163db
Social media post on the subject: https://medium.com/dfohub/core-update-uniswap-integration-staking-and-buidl-2-0-dfohub-weekly-june-13-20-cebba3d106a9 (Section "👁 $buidl 2.0" )

**Comment by Uxio0** [comment]
Done

**Comment by Uxio0** [comment]
I added the new one but didn't remove the old one, at least for now
