### ISSUE TITLE
Add token "PRQ"

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#251]
**Token information**
- Name: Parsiq Token
- Etherscan link: https://etherscan.io/token/0xfe2786d7d1ccab8b015f6ef7392f67d778f8d8d7
- Website (to prevent scam tokens): https://www.parsiq.io/
- Image (at least 200x200, `PNG` if possible) 
![image](https://user-images.githubusercontent.com/1380529/91151416-eb5a6a00-e6bd-11ea-9cef-78bad0b055a3.png)

**Comment by Uxio0** [comment]
Done
