### ISSUE TITLE
Add token "UNI"

### ISSUE THREAD

**Issue by germartinez** [gnosis/safe-relay-service#256]
**Token information**
- Name: Uniswap
- Etherscan link: https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984
- Website (to prevent scam tokens): https://uniswap.org/
- Image (at least 200x200, `PNG` if possible)
https://pbs.twimg.com/profile_images/1242184851152928769/wG2eTAfD_400x400.jpg or https://research.binance.com/static/images/projects/uniswap/logo.png (transparent background)

**Comment by Uxio0** [comment]
Done
