### ISSUE TITLE
Safe V0/V1 on the same array item

### ISSUE THREAD

**Issue by amaurer** [gnosis/safe-relay-service#262]
**Describe the bug**
Safe Valid Contract Addresses seems to have some sort of joining/concat issue with the Safe V0/V1 addresses. I'm not sure what issue this causes yet but it doesn't seem correct. 

![image](https://user-images.githubusercontent.com/561465/97183572-52ef6d00-1774-11eb-9e30-01f5df0012bc.png)

**To Reproduce**
Follow the steps in the Safe Relayer README.md. Docker-compose production directions (not running dev). This relayer is configured to use an Infura Kovan RPC interface. 

**Expected behavior**
A separate array item for each address. 

**Additional context**
Reference of docker Image ID
![image](https://user-images.githubusercontent.com/561465/97183482-39e6bc00-1774-11eb-817e-9ae9cfd2e47f.png)

https://relayer-kovan.trysmartdefi.com/

**Comment by Uxio0** [comment]
Thanks for reporting @amaurer , it was a typo and it has been fixed
