### ISSUE TITLE
Refactor Relay for new version 4.0.0

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-relay-service#264]
# Background 📄 
Relay requirements changed a lot since we started working on it a few years ago. I propose a complete refactor for new version 🕺 **v4.0.0** 💃. 

# Proposal 📓
- Remove `v1/v2/v3` endpoints and reset everything to `v1`. This is confusing for developers using the API and old endpoints are no longer used by anyone (old Gnosis Safe apps are deprecated, more than that, newest versions of the old Gnosis Safe apps were not using the `v1` endpoints).
- Use multiple accounts to send transactions with different priority (`safe-low`, `low`, `standard`, `fast`) instead of one single queue.
- Research using of Gas Tokens: https://gastoken.io/ or https://etherscan.io/token/0x0000000000004946c0e9f43f4dee607b0ef1fa1c . Someone already created a module for the Safes https://twitter.com/emilianobonassi/status/1291758208516857863?s=21
- Remove any trace of `operational_gas` and `data_gas`.
- Support only recent versions of the Safe contracts, Safes >= `v1.1.1`. Of course, older proxies will be supported, so our early adopters don't have to worry as long as they have the Safe contract updated.
- Research check refund payment using `tracing` (before transaction is sent to the queue) so proxies don't need to be checked
- Use `safeTxHash` as main identifier for the transactions. Previously `ethereumTxHash` was used, but transactions can change if `gasPrice` needs to be modified for a stuck transaction.
- Research allowing any payment token with enough liquidity on DEX exchanges.
- Add logic to auto trade back Ether from tokens so in a "perfect world" relay does not need a refill.
- Force refund addresses to the relay ones. The tokens would go to the same account so auto-trading would be easier and more gas efficient.

I would like to hear your opinions about it @tschubotz @lukasschor @rmeissner 😃

**Comment by tschubotz** [comment]
Thanks for this list! 
Before talking about features, I think we should first align on the goals that we would like to reach with the relay, i.e. what use cases do we want to support and what features in the clients do we want to enable?

**Comment by Uxio0** [comment]
> Thanks for this list!
> Before talking about features, I think we should first align on the goals that we would like to reach with the relay, i.e. what use cases do we want to support and what features in the clients do we want to enable?

Of course! This is just a list of ideas I had when thinking on the clients supporting the relay again and that I would like to work in, but this would need to be aligned product wise. 🙂
