### ISSUE TITLE
Calling mainnet get transaction estimate api get 500 error

### ISSUE THREAD

**Issue by mosspig323** [gnosis/safe-relay-service#274]
**Describe the bug**
I have been using gnosis api to send multisig-tx for almost 3 month. 
Since 5 days ago, I can only get 500 each time you call the transaction estimate api. 
Yesterday evening I tried to call manually with same parameters, sometimes it returns correctly sometimes returns 500.

**To Reproduce**
1. POST `https://safe-relay.mainnet.gnosis.io/api/v2/safes/<my_safe_address>/transactions/estimate/`
```
{
"safe":"<safe_address>",
"to":"<contract address>",
"value":"0",
"data":"<data>",
"operation":0
}
```
2. Then GET `Request failed with status code 500`

**Expected behavior**
Get estimate nonce and gasLimit correctly

**Additional context**
No

**Comment by Uxio0** [comment]
Hi, that's not a way I can reproduce the behaviour. You should provide parameters so I can try, and if you don't feel confortable sharing your mainnet information (completely understandable) you can try https://safe-relay.rinkeby.gnosis.io
