### ISSUE TITLE
/v2/safes returns invalid payment token error for valid address in Polygon

### ISSUE THREAD

**Issue by jupiteruwdev** [gnosis/safe-relay-service#317]
**Describe the bug**
I deployed gnosis safe relayer with Polygon and when I try to send request to `/v2/safes` it returns `{
  "exception": "InvalidPaymentToken: 0x0000000000000000000000000000000000001010"
}` even though the payment token address is valid in polygon network.

**To Reproduce**
1. Do POST on '/v2/safes' with this request.
`{
  "saltNonce": 0,
  "owners": [
    "0x8198C81bdE4552344177437Fc5E4Fb0dd7f4eaCE"
  ],
  "threshold": 1,
  "paymentToken": "0x0000000000000000000000000000000000001010"
}`
2. Then GET on `{
  "exception": "InvalidPaymentToken: 0x0000000000000000000000000000000000001010"
}`

**Expected behavior**
It should not say invalid payment token.

**Comment by Uxio0** [comment]
This issue belongs here, not on the tx-service 😉 

To enable a payment token you need to [go to the admin page](https://github.com/gnosis/safe-relay-service#use-admin-interface) `/admin` on the relay service and enable a Token as a payment token. You need to provide also either a fixed price or an oracle.

**Comment by harutoinoue0125** [comment]
> This issue belongs here, not on the tx-service 😉
> 
> To enable a payment token you need to [go to the admin page](https://github.com/gnosis/safe-relay-service#use-admin-interface) `/admin` on the relay service and enable a Token as a payment token. You need to provide also either a fixed price or an oracle.

@Uxio0 I just added token in admin but still getting invalidPaymentToken issue.
any further step needed?

**Comment by jupiteruwdev** [comment]
> This issue belongs here, not on the tx-service 😉
> 
> To enable a payment token you need to [go to the admin page](https://github.com/gnosis/safe-relay-service#use-admin-interface) `/admin` on the relay service and enable a Token as a payment token. You need to provide also either a fixed price or an oracle.

I just added payment token in admin page but still getting invalidPaymentToken issue.
Any further steps needed?

**Comment by Uxio0** [comment]
Did you set `gas=True` for the token?
