### ISSUE TITLE
Prepare some tests to run against rinkeby/mainnet

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-relay-service#59]
## Story
As a developer of the relay service, when I do a release I would like to test rinkeby/mainnet and not just Ganache

## Background
* Currently there's no way clean way of running the tests using a mainnet/rinkeby node
* They require an unlocked node and will spend a lot of ether

## Acceptance criteria
* Some basic tests are run for mainnet/rinkeby (creation of safe, estimating tx, sending of a tx, sending of token...)

## Open questions
* Better to in the continuous integration process or maybe a script that calls the API in some environments and check the results?

**Comment by denisgranha** [comment]
I Would add it as additional tests that are run by the CI when dealing with the master branch? These tests could do client side signing maybe

**Comment by Uxio0** [comment]
Yes, by unlocked nodes I was meaning that now we require that. Problem is that maybe calling then when merging to master is a little overkill, at least for mainnet tests.

**Comment by denisgranha** [comment]
Yeah, was talking about rinkeby ones, maybe mainnet can be done just every 2 weeks or so

**Comment by Uxio0** [comment]
Agree :)

**Comment by Uxio0** [comment]
There are a lot of problems of timeouts testing using rinkeby. A script was created instead to test use cases on a deployed instance of the service
