### ISSUE TITLE
How to propose and sign a transaction with Safe4337Module

### ISSUE THREAD

**Issue by faisal-anwar825** [gnosis/safe-relay-service#600]
I am using a safe that has three owners to send funds to different wallets. Previously i had everything working fine but since i had to maintain the balance in owner wallets in order to pay gas fee. I am trying to implement the relay with Safe4337Module so that the fee is deducted from within the safe itself.

Issue is i couldn't find any documentation about how to propose and sign a transaction from a safe that has multiple owners. I need to implement this for both native and non native tokens. i am using Nestjs and safe contract version "1.4.1+L2".

Could someone from the team point me to the right documentation or code.

**Comment by Uxio0** [comment]
Relay is not maintained anymore, but our transaction service allows signing and collecting signatures for 4337. You can take a look at https://github.com/safe-global/safe-transaction-service/tree/main/safe_transaction_service/account_abstraction

**Comment by faisal-anwar825** [comment]
Is this code available in typescript?

**Comment by Uxio0** [comment]
I encourage you to use our SDK, it supports 4337 and it's written on TypeScript: https://github.com/safe-global/safe-core-sdk

**Comment by faisal-anwar825** [comment]
I am actually using sdk and i need the documentation that guides me to perform this transaction using relay kit. All i could find is this link
[https://docs.safe.global/sdk/relay-kit/guides/4337-safe-sdk](url)
which i am not sure addresses the issue i am facing.

**Comment by Uxio0** [comment]
You should go here for developer support: https://ethereum.stackexchange.com/questions/tagged/safe-core
