### ISSUE TITLE
Provide stats of the service

### ISSUE THREAD

**Issue by Uxio0** [gnosis/safe-relay-service#86]
## Story
As a user of the relay service, I would like to have some stats about the usage of the relay service

## Background
- Data is already there, so it would be desirable to have an endpoint to retrieve some stats of the service

## Acceptance criteria
This sheet contains stats that are worth showing: https://docs.google.com/spreadsheets/d/164rzcQaIJrURGamo5hpNEeLm-PrSB3_QtoHerbpgd7c/edit#gid=0

**Comment by tschubotz** [comment]
Why are there negative times?
- Service uses server time (ntp) for tx creation time.
- Blockchain (miners) use their time to set the "mining" time of block (that includes the tx)
-> somehow sometimes that block time is earlier than the creation time.

Is there another way to calculate the time span from (1) user submitted tx/ tx creation to (2) tx has been executed?
- negative means "instant", i.e. it's included in the next block. So the chart could treat negative number as 0?
- Uxio checks if there is another solution/workaround

**Comment by tschubotz** [comment]
Regarding "Safe deployment times". That actually the "Average time span between the time the user got the address until the tx was executed"

Interesting would also be the time between the moment the user funds the Safe creation and the moment tx execution. This should be relatively instant though since we use "fast".

**Comment by tschubotz** [comment]
Regarding negative token balances: We'll leave it as is for now and see if that's a problem later. Backend would need to listen to all these transfer events.

If on day 1, token A has balance 10, and this didn't change on day 2, the BE currently returns 0 instead of 10. Uxio checks if that can be fixed. Otherwise, we leave it also as is and fix this in the script for now.

**Comment by Uxio0** [comment]
**Regarding "Safe deployment times"**. As @tschubotz pointed, we are currently returning the "Average time span between the time the user got the address until the tx was executed". It would be a little tricky to get that, but it can be done.

**Negative token balances:** That's something very difficult. We can adapt the service for some particular case, like WETH, but it's not trivial, there are some cases like CASH that are more complicated as they don't issue `Transfer` event when people deposit or withdraws funds. I cannot think of a easy workaround, as calling blockchain for every token and every safe (and every block) will be so demanding.

**Returning empty days for stored tokens/eth**: It's have been fixed and will be deployed on monday.

**Timestamp problems**: I still have not figured out what can be going on. Application node and database seem to have the same time (both synced with NTP) but as a preventive measure I will send the timestamp from Django instead of expecting the database to set it. Time differences seem to be minimal.

                             tx_hash                              |            created            |       timestamp        
------------------------------------------------ |-------------------------|------------------------
 506f1fca992cc05d74efd6ccdb0b164713a1e4fa6980e1fffa2ac582502e44b5 | 2019-07-26 10:15:59.327168+00 | 2019-07-26 10:15:31+00
 97993d92da2b5079be1a8146f868ae0247e4f49567b3b739f74450fef28631f3 | 2019-07-26 07:44:47.051888+00 | 2019-07-26 07:44:36+00
 16940b220993598ffaf647ce756300988b7cf8a8d1d43909c110707a63c0a6b5 | 2019-07-25 17:29:44.928587+00 | 2019-07-25 17:29:31+00
 1e12f0638086435c4a2c8f73445141f5d129a92e9dadff0f537fe42659be274a | 2019-07-25 14:30:33.063306+00 | 2019-07-25 14:30:23+00
 33eb81698f30a864b043e32c328c1ce7514437289ba91a9efd582652e494f65f | 2019-07-25 12:29:02.999981+00 | 2019-07-25 12:29:01+00
 0369be71441d234fc93f6ee1e3fd9c6c56f832f0d8159b2957b942395846658c | 2019-07-25 10:17:39.067824+00 | 2019-07-25 10:17:39+00                                                                                                                                                      
 83607f122d3e2511b3d55727fa58ec3c6f19eee1b444d47c814156437ea79d87 | 2019-07-25 06:26:25.13472+00  | 2019-07-25 06:26:12+00
 5781e61221ef6a122128b9de76fa71830826c3bffe70fddc74f5d5dfff9ca1a1 | 2019-07-24 23:27:26.525531+00 | 2019-07-24 23:27:26+00
 6ae37455963144e9479e4a1332f8b831b40037063caee476001c5709677a34c8 | 2019-07-24 20:21:18.320906+00 | 2019-07-24 20:21:14+00
 8ca25a0b0079e016aef1ba41b38c8e9fb9a6d091cf063fc832f88d30ea459224 | 2019-07-24 15:39:49.719029+00 | 2019-07-24 15:39:49+00

**Comment by Uxio0** [comment]
"Safe deployment times": It has been fixed. Now there are 2 values.

- `averageDeployTimeSeconds`: time that the Safe took to be created since the user funded it
- `averageDeployTimeTotalSeconds`: time that the Safe took to be created since the user requested the creation
