### ISSUE TITLE
New tokens

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#87]
### DATAcoin
That token is already in our token list. Could you please change the symbol from DATAcoin to DATA? (That's what they have on etherscan: https://etherscan.io/token/0x0Cf0Ee63788A0849fE5297F3407f701E122cC023)

### GSENetwork
Coud you please add the following token (https://etherscan.io/token/0xe530441f4f73bDB6DC2fA5aF7c3fC5fD551Ec838)
- Address: 0xe530441f4f73bDB6DC2fA5aF7c3fC5fD551Ec838
- Name: GSENetwork
- Symbol: GSE
- Decimals: 4
- website: https://gse.network/
- logo: https://res-2.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/hxxyznv7e1zjlxmv2x35 (Couldn't find a better one 😬 )

**Comment by Uxio0** [comment]
@tschubotz Done

https://safe-relay.gnosis.pm/api/v1/tokens/?search=datacoin
https://safe-relay.gnosis.pm/api/v1/tokens/?search=GSENetwork

**Comment by tschubotz** [comment]
@cag ☝️ fyi :)

**Comment by cag** [comment]
@tschubotz @Uxio0 Any way I can get a picture for DATA? ;)

https://gnosis-safe-token-logos.s3.amazonaws.com/0x0Cf0Ee63788A0849fE5297F3407f701E122cC023.png gives me nothing rn...

**Comment by Uxio0** [comment]
I've updated Datacoin image https://gnosis-safe-token-logos.s3.amazonaws.com/0x0Cf0Ee63788A0849fE5297F3407f701E122cC023.png :)
