### ISSUE TITLE
Add Compound tokens

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#93]
Please add the compound tokens to our token list:

- Compound BAT (cBAT) https://etherscan.io/token/0x6c8c6b02e7b2be14d4fa6022dfd6d75921d90e4e
- Compound Dai (cDAI) https://etherscan.io/token/0xf5dce57282a584d2746faf1593d3121fcac444dc
- Compound Ether (cETH) https://etherscan.io/token/0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5
- Compound Augur (cREP) https://etherscan.io/token/0x158079ee67fce2f58472a96584a73c7ab9ac95c1
- Compound USD Coin (cUSDC) https://etherscan.io/token/0x39aa39c021dfbae8fac545936693ac917d5e7563
- Compound Ox (cZRX) https://etherscan.io/token/0xb3319f5d18bc0d84dd1b4825dcde5d5f7266d407

They all have 8 decimals.
URL: 
https://compound.finance/ 

Icons can be found at https://drive.google.com/drive/folders/1UhTswCEgzsokHQKLnTv4kyxhU70V9Wxm

**Comment by Uxio0** [comment]
Added https://safe-relay.gnosis.pm/api/v1/tokens/?search=compound
