### ISSUE TITLE
Add LRC v2 token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#95]
Please add the LRC v2 token to our relay service: https://etherscan.io/token/0xbbbbca6a901c926f240b89eacb641d8aec7aeafd

**Comment by tschubotz** [comment]
I reached out to them to get the image.

**Comment by tschubotz** [comment]
Logo: https://drive.google.com/drive/folders/1mRUOoGO6Uj6hveFBbbGjOHEnNf4uo6qe (LRC blue fill)

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.pm/api/v1/tokens/?search=LoopringCoin
