### ISSUE TITLE
Add OCEAN token

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-relay-service#97]
Please add the OCEAN token to our token list https://etherscan.io/address/0x985dd3d42de1e256d09e1c10f112bccb8015ad41

Logo: https://drive.google.com/open?id=1G7nWocv7Zhg0HJaDjwLfVzE_c-pyzSxQ

**Comment by Uxio0** [comment]
https://safe-relay.gnosis.pm/api/v1/tokens/?search=OCEAN
